Update zangar_nurda.yml

diff --git a/.github/workflows/zangar_nurda.yml b/.github/workflows/zangar_nurda.yml
--- a/.github/workflows/zangar_nurda.yml
+++ b/.github/workflows/zangar_nurda.yml
@@ -1,4 +1,4 @@
-name: Nurda ci/cd
+name: Nurda Zangar ci/cd
 
 on:
   push:
@@ -42,25 +42,53 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-      - name: Verify Docker Hub Login
-        run: |
-          docker info
-          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  # Test login explicitly
-
+      # Step to log in to Docker Hub
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-          registry: index.docker.io  # Docker Hub registry URL (default)
+          username: ${{ secrets.DOCKER_USERNAME }}  # Use your Docker Hub username
+          password: ${{ secrets.DOCKER_PASSWORD }}    # Use your Docker Hub token
 
-    
+      - name: Generate Docker Metadata
+        id: meta
+        uses: docker/metadata-action@v4
+        with:
+          images: ${{ secrets.DOCKER_USERNAME }}/cloud-gh-actions-workshop  # Replace with your Docker Hub repository name
+          tags: |
+            type=ref,event=tag
+            type=ref,event=pr
+            type=sha,event=branch,prefix=,suffix=,format=short
 
       - name: Build and Push Docker Image
         uses: docker/build-push-action@v2
         with:
           push: true
-          tags: ${{ secrets.DOCKER_USERNAME }}/nurda-dh-actions-workshop:latest  # Replace with your Docker Hub repository name
+          tags: ${{ secrets.DOCKER_USERNAME }}/cloud-gh-actions-workshop:latest  # Replace with your Docker Hub repository name
           labels: ${{ steps.meta.outputs.labels }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
+
+  deploy:
+    needs:
+      - package-and-publish  # Ensure CD only runs after CI and packaging are done
+    runs-on: self-hosted  # This will use your self-hosted runner
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+  
+      - name: Pull Docker Image
+        run: |
+          # Pull the latest image from Docker Hub
+          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cloud-gh-actions-workshop:latest
+  
+      - name: Deploy Docker Container
+        run: |
+          # Gracefully stop and remove the old container if exists
+          sudo docker stop my-container || true
+          sudo docker rm my-container || true
+          
+          # Run the new container
+          sudo docker run -d --name my-container -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/cloud-gh-actions-workshop:latest
+  
+          # Clean up unused Docker resources
+          sudo docker system prune -f
